version: '3'

services:
  irc:
    image: inspircd/inspircd-docker
    ports:
      - "6667:6667"
  package:
    image: electronuserland/builder
    volumes:
      - ./:/project
    command: npm run package